baseurl = "https://bootstrap-guidelines.herokuapp.com/"
languageCode = "en-us"
title = "Bootstrap"
theme = "blackburn"
canonifyurls = true

[params]
  custom_css = ["css/bootstrap.min.css","css/style.css"]
  custom_js = ["js/jquery.min.js","js/bootstrap.min.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Introduction"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "introduction"
    url = "/post/introduction"
  [[menu.main]]
    name = "Grid System"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "gridsystem"
    url = "/post/gridsystem"
  [[menu.main]]
    name = "Customization"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 4
    identifier = "customization"
    url = "/post/customization"
  [[menu.main]]
    name = "Speeding Up"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 5
    identifier = "speedingup"
    url = "/post/speedingup"
